id = "prisma"
name = "Prisma"
description = "Prisma support."
version = "0.1.2"
schema_version = 1
authors = ["Matthew Gramigna <matthewgramigna@gmail.com>", "Victor Quiroz <git@victorhqc.com>"]
repository = "https://github.com/zed-extensions/prisma"

[language_servers.prisma-language-server]
name = "Prisma Language Server"
language = "Prisma"

[grammars.prisma]
repository = "https://github.com/dstrygwyr/zed-tree-sitter-prisma"
commit = "5d362efe9582256a8194086123ef86db6cbdb4c5"
